languageCode: "en-us"
baseUrl: "https://techdebug.com/"
title: "Tech Debug"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

params:
  style: auto
  social:
  - id: github
    name: lantrix
  - id: spotify
    name: lantrix
