languageCode: "en-us"
baseUrl: "https://techdebug.com/"
title: "Tech Debug"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

params:
  cloudfrontId: foobar
  style: auto
  social:
    - id: github
      name: lantrix
    - id: spotify
      name: lantrix

taxonomies:
  category: categories
  tag: tags

permalinks:
  posts: "/blog/:year/:month/:slug/"
  archm: "/blog/:year/:month/"
  archy: "/blog/:year/"
  term:
    tags: /tag/:slug/
    categories: /blog/category/:slug/

deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: techdebug
      URL: s3://techdebug.com
      cloudFrontDistributionID: "{{ $.Site.Params.cloudfrontId }}"
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: max-age=31536000, no-transform, public
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: max-age=31536000, no-transform, public
      gzip: false
    - pattern: ^sitemap\.xml$
      contentType: application/xml
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
